#!/usr/bin/env bash
# Install and configure nginx on a web server and  redirects


config_file="/etc/nginx/nginx.conf"
root_path="/data/www/"

config_content=$(cat << EOF
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {
	server {
		listen         80 default_server;
		listen         [::]:80 default_server;
		server_name    theegsd.tech www.theegsd.tech;
		root           $root_path;
		index          index.html;
		location / {
			root $root_path;

		}
	}
}
EOF
)

index_content="Hello World!"

echo "Installing nginx server..."
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

# echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html

echo "Creating the web root folder @ $root_path"
mkdir -p "$root_path"
echo "$index_content" > "$root_path/index.html"

echo "Adding the configuration file @ $config_file"
echo "$config_content" > "$config_file"

sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default


echo "Starting the server..."


service nginx start

if [ "$?" == "0" ]; then
	echo "Server Started successfully"
else
	echo "Unable to start the server for some reason"
fi
