#!/usr/bin/env bash
# Installs, configures an nginx server to redirect on a web server

config_file="/etc/nginx/nginx.conf"
root_path="/data/www/"

config_content=$(cat << EOF
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

http {
        server {
                listen         80 default_server;
                listen         [::]:80 default_server;
                server_name    theegsd.tech www.theegsd.tech;
                root           $root_path;
                index          index.html;
		error_page 404 /404.html;

                location / {
                        root $root_path;

                }

		location /redirect_me {
			return 301 http://cuberule.com/;
		}

		location /404 {
			root /etc/nginx/html;
			internal;
		}
        }
}
EOF
)


index_content="Hello World!"

echo "Installing nginx server..."
apt-get -y update
apt-get -y install nginx
ufw allow "Nginx HTTP"

# echo "Creating the web root folder @ $root_path"
mkdir -p "$root_path"
echo "$index_content" > "$root_path/index.html"

# echo "Adding the configuration file @ $config_file"
echo "$config_content" > "$config_file"

echo "Ceci n'est pas une page" > "$root_path/404.html"

# echo "Starting the server..."

service nginx start
