#!/usr/bin/env bash
# This scripts debugs a server and restarts it
sudo apt-get -y update && sudo apt-get -y install nginx
sudo sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx stop
sudo service nginx start
