#!/usr/bin/env bash
# Some random script sha

echo "$$" > /var/run/myscript.pid

while :
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I hate the kill command"; rm /var/run/myscript.pid' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid' SIGQUIT
done
