#!/usr/bin/env bash
# Manages another process called manage_my_process

if [ "$1" == "start" ];
then
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "$1" == "stop" ];
then
	pkill --signal KILL -f ./manage_my_process
	rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ];
then
	pkill --signal KILL -f ./manage_my_process
        rm /var/run/my_process.pid
	./manage_my_process &
        echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
