#!/usr/bin/env bash
# /etc/passwd file manipulation

filename="/etc/passwd"

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7;
do

	printf "The user %s is part of the %s gang, " "$f1" "$f4"
	printf "lives in %s and rides %s. " "$f6" "$f7"
	printf "%s's place is protected by the passcode %s, " "$f3" "$f2"
	printf "more info about the user here: %s\n" "$f5"
done < $filename
