#!/usr/bin/bash env
# Runs nginx as a user named nginx
pkill apache2
chmod -R 777 /etc/nginx/
sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx nginx -c /etc/nginx/nginx.conf
